"""Supervised neural-network agents for 2048.

The model learns a policy from expert labels generated by the heuristic agent.
Inputs use the board's log2 encoding: empty=0, 2=1, 4=2, ...
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

from agent.base import Agent
from game.board import Board, UP

try:
    import torch
    from torch import nn
except ImportError as exc:  # pragma: no cover - depends on local ML env
    torch = None
    nn = None
    _TORCH_IMPORT_ERROR = exc
else:
    _TORCH_IMPORT_ERROR = None

NUM_ACTIONS = 4
DEFAULT_NORMALIZE_BY = 16.0


def require_torch() -> None:
    if torch is None or nn is None:
        raise ImportError(
            "PyTorch is required for the supervised neural-network agent. "
            "Install torch before training or loading this agent."
        ) from _TORCH_IMPORT_ERROR


def encode_board(
    board: Board,
    normalize_by: float = DEFAULT_NORMALIZE_BY,
) -> np.ndarray:
    """Return a flat float32 feature vector with 16 log2-encoded cells."""
    state = board.get_state().astype(np.float32, copy=False).reshape(16)
    if normalize_by:
        state = state / float(normalize_by)
    return state


def valid_action_mask(board: Board) -> np.ndarray:
    """Return a bool mask in action order 0=up, 1=down, 2=left, 3=right."""
    mask = np.zeros(NUM_ACTIONS, dtype=np.bool_)
    for action in board.get_valid_moves():
        mask[int(action)] = True
    return mask


class SupervisedMLP(nn.Module if nn is not None else object):
    """Small MLP policy network for a flattened 4x4 board."""

    def __init__(
        self,
        hidden_sizes: tuple[int, int, int] = (128, 128, 64),
    ) -> None:
        require_torch()
        super().__init__()
        layers: list[nn.Module] = []
        in_features = 16
        for hidden_size in hidden_sizes:
            layers.append(nn.Linear(in_features, hidden_size))
            layers.append(nn.ReLU())
            in_features = hidden_size
        layers.append(nn.Linear(in_features, NUM_ACTIONS))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.ndim > 2:
            x = x.reshape(x.shape[0], -1)
        return self.net(x)


class SupervisedCNN(nn.Module if nn is not None else object):
    """Lightweight CNN policy network for optional comparison."""

    def __init__(self) -> None:
        require_torch()
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=2),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=2),
            nn.ReLU(),
        )
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 2 * 2, 128),
            nn.ReLU(),
            nn.Linear(128, NUM_ACTIONS),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.ndim == 2:
            x = x.reshape(x.shape[0], 1, 4, 4)
        return self.head(self.features(x))


def build_model(model_type: str) -> Any:
    """Create a supervised policy model."""
    require_torch()
    normalized = model_type.lower()
    if normalized == "mlp":
        return SupervisedMLP()
    if normalized == "cnn":
        return SupervisedCNN()
    raise ValueError(f"Unsupported model_type: {model_type!r}")


def resolve_device(device: str = "auto") -> Any:
    """Resolve a torch device, preferring CUDA in auto mode."""
    require_torch()
    if device == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    resolved = torch.device(device)
    if resolved.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested, but torch.cuda.is_available() is False")
    return resolved


def load_policy_checkpoint(
    path: str | Path,
    model_type: str | None = None,
    device: str = "auto",
) -> tuple[Any, dict[str, Any], Any]:
    """Load a supervised policy checkpoint and return model, metadata, device."""
    require_torch()
    resolved_device = resolve_device(device)
    checkpoint = torch.load(Path(path), map_location=resolved_device)

    if isinstance(checkpoint, dict) and "model_state" in checkpoint:
        metadata = dict(checkpoint.get("metadata", {}))
        checkpoint_model_type = checkpoint.get("model_type") or metadata.get("model_type")
        selected_model_type = model_type or checkpoint_model_type or "mlp"
        model = build_model(selected_model_type)
        model.load_state_dict(checkpoint["model_state"])
    else:
        selected_model_type = model_type or "mlp"
        metadata = {"model_type": selected_model_type}
        model = build_model(selected_model_type)
        model.load_state_dict(checkpoint)

    metadata.setdefault("model_type", selected_model_type)
    metadata.setdefault("normalize_by", DEFAULT_NORMALIZE_BY)
    model.to(resolved_device)
    model.eval()
    return model, metadata, resolved_device


class NeuralNetworkAgent(Agent):
    """Agent wrapper around a trained supervised policy network."""

    def __init__(
        self,
        model_path: str | Path,
        model_type: str | None = None,
        device: str = "auto",
    ) -> None:
        self.model, self.metadata, self.device = load_policy_checkpoint(
            model_path,
            model_type=model_type,
            device=device,
        )
        self.model_type = str(self.metadata.get("model_type", model_type or "mlp"))
        self.normalize_by = float(
            self.metadata.get("normalize_by", DEFAULT_NORMALIZE_BY)
        )

    def get_action(self, board: Board) -> int:
        valid_mask = valid_action_mask(board)
        if not valid_mask.any():
            return UP

        features = encode_board(board, normalize_by=self.normalize_by)
        with torch.no_grad():
            x = torch.from_numpy(features).unsqueeze(0).to(self.device)
            if self.model_type == "cnn":
                x = x.reshape(1, 1, 4, 4)
            logits = self.model(x).squeeze(0)
            mask = torch.as_tensor(valid_mask, dtype=torch.bool, device=self.device)
            logits = logits.masked_fill(~mask, -1.0e9)
            return int(torch.argmax(logits).item())
